[package]
org = "mohom"
name = "pocket_dictionary"
version = "0.1.0"
distribution = "2201.12.6"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "http"
version = "2.14.4"

[[dependency]]
org = "ballerina"
name = "log"
version = "2.9.1"

[[dependency]]
org = "ballerina"
name = "time"
version = "2.4.0"